using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TOF.Framework.Data.Annotations;

namespace Ranger.TestConsole
{
    [Table("Candidates")]
    public class Candidate
    {
        [JsonProperty("id")]
        [Key]
        [AutoGenerated]
        [DbType(DbType.Guid)]
        public string Id { get; set; }
        public string TakerNumber { get; set; }
        [DataColumnName("NameCHT")]
        public string NameCht { get; set; }
        [DataColumnName("NameENG")]
        public string NameEng { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public byte[] Password { get; set; }
        public byte[] Data { get; set; }
        public string RegSource { get; set; } // from facebook or manual.
        [AllowNull]
        public string RegSourceId { get; set; } // social login user ID.
        [AutoGenerated]
        public DateTime DateCreated { get; set; }
        [AutoGenerated]
        public DateTime DateLastMod { get; set; }
    }
}
