using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Text;

namespace TOF.Framework.Data
{
    public class DefaultPropertyBindingInfo : IPropertyBindingInfo
    {
        private PropertyInfo _propertyInfo = null;
        private string _name = null;
        private DbType? _dbType = null;
        private int? _length = null;
        private bool _isKey = false;
        private bool _allowNull = false;
        private bool _isIncremental = false;
        private bool _isAutogenerated = false;

        public DefaultPropertyBindingInfo(PropertyInfo PropertyInfo)
        {
            this._propertyInfo = PropertyInfo;
            this._name = this._propertyInfo.Name;
        }

        public PropertyInfo GetPropertyInfo()
        {
            return this._propertyInfo;
        }

        public string GetParameterName()
        {
            return this._name;
        }

        public DbType? GetMapDbType()
        {
            return this._dbType;
        }

        public int? GetLength()
        {
            return this._length;
        }

        public bool IsKey()
        {
            return this._isKey;
        }

        public bool IsAllowNull()
        {
            return this._allowNull;
        }

        public bool IsIncremental()
        {
            return this._isIncremental;
        }

        public bool IsAutoGenerated()
        {
            return this._isAutogenerated;
        }

        public IPropertyBindingInfo DbName(string Name)
        {
            this._name = Name;
            return this;
        }

        public IPropertyBindingInfo AsKey()
        {
            this._isKey = true;
            return this;
        }

        public IPropertyBindingInfo MapDbType(DbType Type)
        {
            this._dbType = Type;
            return this;
        }

        public IPropertyBindingInfo AllowNull()
        {
            this._allowNull = true;
            return this;
        }

        public IPropertyBindingInfo AsIncremental()
        {
            this._isIncremental = true;
            return this;
        }

        public IPropertyBindingInfo AsAutoGenerated()
        {
            this._isAutogenerated = true;
            return this;
        }

        public IPropertyBindingInfo MaxLength(int Length)
        {
            this._length = Length;
            return this;
        }
    }
}
