using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Text;

namespace TOF.Framework.Data
{
    public interface IPropertyBindingInfo
    {
        PropertyInfo GetPropertyInfo();
        string GetParameterName();
        DbType? GetMapDbType();
        int? GetLength();
        bool IsKey();
        bool IsAllowNull();
        bool IsIncremental();
        bool IsAutoGenerated();
        IPropertyBindingInfo DbName(string Name);
        IPropertyBindingInfo AsKey();
        IPropertyBindingInfo MapDbType(DbType Type);
        IPropertyBindingInfo AllowNull();
        IPropertyBindingInfo AsIncremental();
        IPropertyBindingInfo AsAutoGenerated();
        IPropertyBindingInfo MaxLength(int Length);
    }
}
